export const SET_ADMIN = 'SET_ADMIN'
export const SET_ADMIN_ERROR = 'SET_ADMIN_ERROR'


export const SET_CUSTOMER = 'SET_CUSTOMER'
export const SET_CUSTOMER_ERROR = 'SET_CUSTOMER_ERROR'
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR'


export const ADD_TO_BUSKET = 'ADD_TO_BUSKET'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const ORDERED_PRODUCTS = 'ORDERED_PRODUCTS'


export const ADMIN_AUTH = 'ADMIN_AUTH'
export const ADMIN_ERROR = 'ADMIN_ERROR'


export const SIDE_BARS = 'SIDE_BARS'






export const GET_NUMBERS_BUSKET = 'GET_NUMBERS_BUSKET'















